# 2026


class SQLiteIndexer:
    """SQLite index for cached torrent results."""

    def __init__(self, db_path: str): ...

    def create_db(self): ...

    def insert(self, torrent): ...

    def search(self, query: str): ...

    def match_tmdb(self, tmdb_id: int): ...

    def get_stale(self, days: int = 7): ...

    def delete_stale(self, days: int = 7): ...

    def log_sync(self, source: str, count: int): ...
